### ISSUE TITLE
Add support for generating JSON

### ISSUE THREAD

**Issue by GalaJames** [galatea-associates/fuse-test-data-gen#1]

**Comment by GalaJames** [comment]
Created a new class JSONBuilder that implements the new FileBuilder abstract class.  The JSONBuilder class contains the logic required to write a list of dictionaries to a JSON file.

**Comment by j-barber** [comment]
Can you include a link to the output json files (preferably put the output in a new folder here: https://drive.google.com/drive/folders/1xsYjtAalsYmC9qElPI9DnxllGB7sYSVL)

**Comment by GalaJames** [comment]
Files have been uploaded in a dedicated folder here:

https://drive.google.com/drive/folders/109q4JgBP2-Qrjxj_rAp9YYffzM5kWbHm
