### ISSUE TITLE
Instruments: Don't assign '0' for sedol/cusip for Cash

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#12]
![image](https://user-images.githubusercontent.com/23705265/59692125-4cc9a380-91b2-11e9-99ff-96ea63df70c7.png)

**Comment by GalaJoe** [comment]
Amended return value of "generate_sedol" and "generate_cusip" from 0 to ''

**Comment by j-barber** [comment]
Can you include a link to the output files showing this is resolved (preferably put the output in a new folder here: https://drive.google.com/drive/folders/1xsYjtAalsYmC9qElPI9DnxllGB7sYSVL)?

**Comment by GalaJoe** [comment]
Output file showing resolution has been uploaded to: https://drive.google.com/drive/folders/1IqKchlbfVd0HpCHXVbC70UqGb12Rk_9d
