### ISSUE TITLE
Instruments: RIC suffix, ISIN prefix, and COI should agree

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#13]
e.g. DTRM.FR should have ISIN prefix FR and COI FR

![image](https://user-images.githubusercontent.com/23705265/59693254-9915e300-91b4-11e9-8c38-f0d22488851f.png)

**Comment by GalaJoe** [comment]
RIC Exchange Codes from: http://training.thomsonreuters.com/portal/docs/pdf/raymondjames/Thomson_One_Exchange_List.pdf

**Comment by GalaJoe** [comment]
RIC Exchange codes sourced from: http://training.thomsonreuters.com/portal/docs/pdf/raymondjames/Thomson_One_Exchange_List.pdf

Country Codes sourced from: https://www.isin.net/country-codes/


RIC is the first attribute generated within instrument. Part of this is a random choice of which exchange is being traded on. This exchange code is then used to lookup the Country which that exchange is in and assigns COI to that value immediately. 

Expected & Output results: https://drive.google.com/drive/u/0/folders/1NdJ2iTOlULHhq2cJCgxTUrOMe4CDKr1p

**Comment by GalaJames** [comment]
I've re-fixed this since the refactor.  The latest instruments_001.csv in the following folder contains this fix:

https://drive.google.com/drive/folders/1NdJ2iTOlULHhq2cJCgxTUrOMe4CDKr1p
