### ISSUE TITLE
Back Office Positions: ED should not be greater than KD for TD positions

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#14]
TD positions should always have ED <= KD (and generally just ED=KD).

https://drive.google.com/drive/folders/1IcuDZAx58zzp5Q4BI6G7Xxd01NTmTfjk
![image](https://user-images.githubusercontent.com/23705265/59695061-98328080-91b7-11e9-8fc7-ae9b0c24ef9c.png)

**Comment by GalaJoe** [comment]
Rectified by altering the number of days added to calculate the ED from 3 to 0. Evidence at: https://drive.google.com/drive/u/0/folders/1v6q01rH2P7cOHDYb_mKKuZscvWUKnRzP
