### ISSUE TITLE
Modify Price generation to be dependant on Instruments and Exchnage information

### ISSUE THREAD

**Issue by tonasanya** [galatea-associates/fuse-test-data-gen#144]
Issue Description
---
Modify the generation of prices to be dependant on instruments. 

Design
---
- When creating a price, get a real instrument from the database and store it's country of issue and instrument Id. 

- Use the countryOfIssue to query the ExchangeInfo for the currency.

Documentation Changes
---
Update the Price numpy documentation. 
Update the README with the new dependency.

Test Evidence
---

All price related tests still pass

Validation in Develop
---
Ensure prices can still be made

**Comment by GalateaTom** [comment]
Change has been made and pushed.  However PR has not been raised as change reflects the current status where an instrument is identified by a RIC, but once the correct domain model has been implemented we will need to update this branch as we expect InstrumentId will become an instrument's unique identifier.
Currently blocked.
