### ISSUE TITLE
Back Office Positions: don't create ECP positions

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#15]
ECP positions generally aren't kept in a books and records type position feed.

https://drive.google.com/drive/folders/1IcuDZAx58zzp5Q4BI6G7Xxd01NTmTfjk
![image](https://user-images.githubusercontent.com/23705265/59695429-39b9d200-91b8-11e9-9060-a3199edfe5b3.png)

**Comment by GalaJoe** [comment]
ECP Accounts can no longer be generated within Back Office Domain Objects.

Evidence can be seen at: https://drive.google.com/drive/u/0/folders/1I1GoXjPm7kHCmR_TYbCbbBZB2JGPKKtL
