### ISSUE TITLE
Depot Positions: Depot by Account?

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#16]
Are we intending to support Depot By Account? If not, we should remove the Account field (since there's already a depot_id field)

https://drive.google.com/drive/folders/1IcuDZAx58zzp5Q4BI6G7Xxd01NTmTfjk
![image](https://user-images.githubusercontent.com/23705265/59695968-1d6a6500-91b9-11e9-9bb8-bebd2ee9f231.png)

**Comment by GalaJoe** [comment]
Issue re-opened with decision made to remove account field in Issue 48
