### ISSUE TITLE
Depot Positions: remove 'Direction' and 'Position Type' fields

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#17]
Depot positions are always "what's in the box", so don't need a position type or direction (and DR is illogical).

https://drive.google.com/drive/folders/1IcuDZAx58zzp5Q4BI6G7Xxd01NTmTfjk
![image](https://user-images.githubusercontent.com/23705265/59696317-c022e380-91b9-11e9-8b9a-7543a317b7fa.png)

**Comment by GalaJoe** [comment]
Validation of removal can be found at: https://drive.google.com/drive/u/0/folders/1LoeWnpUp7J3qjkP-qe-gUGrQ0JlHbSHo
