### ISSUE TITLE
Instrument Data Model

### ISSUE THREAD

**Issue by WilfGala** [galatea-associates/fuse-test-data-gen#173]
## Issue Description
Following discussions about the first iteration of domain object data models, a series of changes have been proposed. The attribute specification for records generated by the `InstrumentFactory` class has been changed, and must be implemented as detailed in the _Data Generator Attributes_ document in the Google Drive folder.

Closing this issue closes #67 

### instrument_factory.py

The `create()` method of the `InstrumentFactory` class from `instrument_factory.py` should be amended to ensure that the generated records contain only the attributes given in the table below:

Attribute | Action
--- | ---
Instrument ID | No Change
RIC | No Change
ISIN | No Change
SEDOL | No Change
Ticker | No Change
CUSIP | No Change
Valoren | New
Quick | New
Sicovam | New
Asset Class | Amend Existing
Asset SubClass | New
Country of Issuance | No Change
Primary Market | New
Market | New
IsPrimaryListing | New
Bloomberg Company Identifier | New
Issuer Name | New
Industry Classification | New
Created TimeStamp | New
Last Updated TimeStamp | New

For details of expected values and attributes to be removed, please see the _Data Generator Attributes_ document in the Google Drive folder.

### instrument_test.py

The `instrument_test.py` file should have additional tests added to validate the existence and value of  all new attributes. The value of the _quantity_ parameter passed to the `attribute_quantity_valid()` function should be changed after tests are updated to reflect the new number of attributes.

## Documentation Changes
Any docstrings recording class or record attributes should be updated where appropriate.

## Test Evidence
All tests in the amended `instrument_test.py` file should pass, and instruments should be built using all existing file builders to check output is as expected.

## Validation in Develop
Not needed if test pass.

**Comment by GalateaTom** [comment]
From my research I can see that the Bloomberg Company Identifier has been replaced by something called a FIGI, so I have included that in the Instrument instead

**Comment by GalateaTom** [comment]
In the ASSET_CLASS list I set Right and Warrant to be types of Derivative rather than types of Equity, as I felt that was more accurate
