### ISSUE TITLE
Add support for generating XML

### ISSUE THREAD

**Issue by GalaJames** [galatea-associates/fuse-test-data-gen#2]

**Comment by Gala-Gerrard** [comment]
Used the dictotoxml library to output XML files from python dictionaries - the library is not the most flexible, therefore could in future implement a custom xml generator in order to handle attributes such as element properties and nested elements.

**Comment by j-barber** [comment]
Can you include a link to the output xml files (preferably put the output in a new folder here: https://drive.google.com/drive/folders/1xsYjtAalsYmC9qElPI9DnxllGB7sYSVL)

**Comment by GalaJames** [comment]
Files have been uploaded to a dedicated folder here: https://drive.google.com/drive/folders/1RMdw9m03gDNV5Xy7KBeObLZCs6Kr8UCU

**Comment by j-barber** [comment]
Is it possible to have the xml elements in the output match the datatypes being output, so instead of 
`<list_item>...</list_item>`
we end up with
`<instrument>...</instrument>`

**Comment by GalaJames** [comment]
This has now been fixed, files are here:

https://drive.google.com/drive/folders/1RMdw9m03gDNV5Xy7KBeObLZCs6Kr8UCU

I've made this configurable via the JSON config with the following two attributes and updated the readme to reflect this:

```
"root_element_name":"instruments",
"item_name":"instrument"
```
