### ISSUE TITLE
Back Office Positions: use instruments from instruments dataset

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#21]
The CUSIPs on the Back Office Positions dataset should be represented in the Instrument dataset.

See issue #8 for an example.

**Comment by GalaJoe** [comment]
Resolved, evidenced at: https://drive.google.com/drive/u/0/folders/1MGms2tbEnQF1Tnp9loGZ_bP4RnV9EEYE
