### ISSUE TITLE
Depot Positions: use instruments from instruments dataset

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#22]
The ISINs on the Depot Positions dataset should be represented in the Instrument dataset.  See issue #8 for an example.

**Comment by GalaJoe** [comment]
Evidenced at: https://drive.google.com/drive/u/0/folders/1YpV-eCN0Nz8P04usdWyxzQkgTnL-hTms

Seemingly inadvertent fix, no code changes.
