### ISSUE TITLE
Allow multiple config files

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-test-data-gen#25]
We should allow ourselves to have multiple pre-set configurations, selectable via the command line (with a sensible default).

**Comment by GalaJames** [comment]
Added an optional command line argument called "--config".  If you pass this with the file location of a valid JSON config file, that config file will be used.  Otherwise it will default to the config file that is current in Git.

**Comment by j-barber** [comment]
Can you include some instructions and an example in the readme?

**Comment by GalaJames** [comment]
I have added the following to the readme, this can be found on the feature/issue-25-multiple-configs branch:

### Specifying a custom config file
By default, the application will run using the config.json file in the root of the src directory.  It is possible to maintain multiple config files and specify which to use via an optional command line argument.  For example, running the data generator as follows will use a custom JSON config file:

```python src/app.py --config src/my_custom_config.json```

Your custom config will need to contain at least one domain object configuration and one file builder configuration as show in the configuration section above.
