### ISSUE TITLE
Prefix padding fields with domain object name and allow number of fields to be configurable

### ISSUE THREAD

**Issue by GalaJames** [galatea-associates/fuse-test-data-gen#27]
Kyle has asked that the additional padding fields (field1, field2 etc) are prefixed with the domain object name (e.g. instrument_field1, instrument_field2 etc).  It would also be useful to allow the number of fields to be configurable via the config.json.

**Comment by GalaJoe** [comment]
This issue has 2 portions, the padding of domain object names is complete. As for the second:

Configuration does have an option for a user-specified number of dummy fields. 
Currently, where required, dummy fields are hard-coded into the generation methods of domain objects (Counterparties & Swap Contracts).
Alter this approach to leverage the configuration file and generate a user-given amount of them on an ad-hoc basis.
