### ISSUE TITLE
Refactor to allow for easier adding of new domain objects

### ISSUE THREAD

**Issue by GalaJames** [galatea-associates/fuse-test-data-gen#3]

**Comment by GalaJames** [comment]
Created a new abstract class "Generatable" which all domain object classes will need to implement.  
Created a separate package containing a module per domain object and separated out the template dictionaries from the original DataGenerator class.
Renamed DataGenerator.py to app.py and refactored code to support new domain objects structure.

**Comment by j-barber** [comment]
Sounds good -- will marked 'Reviewer Approved' post our architecture/code review later this week.
