### ISSUE TITLE
Back Office and Front Office Positions Should have ICP Accounts and ECP Counterparties

### ISSUE THREAD

**Issue by GalaJoe** [galatea-associates/fuse-test-data-gen#49]
Issue Description
---
Currently, back & front office positions will only ever generate ICP accounts. We should add a counterparty field also which should be populated with an ECP account

Design
---
Account and Counterparty field should be dependant on the new 'Account' domain object. Account should randomly select an ICP account and Counterparty and ECP account.

Documentation Changes
---
Extend the definition of the account attribute for back office and front office positions within the Data Generator Attributes document, https://docs.google.com/document/d/1IB_-k16uhSBJWg2_s0pD2Vh3WZjTFALFYV6Ip9jM_4Q/edit?usp=sharing

Add counterparty attribute to the doc for front and back offfice positions

Test Evidence
---
Within "Back / Front Office Position Tests", currently a check is made to verify the account attribute is ICP only. Extend this test to check whether the counterparty field is ECP aswell

Validation in Develop
---
Generate a set of Back Office and Front office Positions showing that the account is genereated as an ICP and the counterparty field is generated as an ECP

**Comment by GalateaTom** [comment]
Changes committed to fulfill the requirements in this issue, but pull request will not be raised yet because there are outstanding questions on the fuse-test-data-gen channel about what kind of account should hold back office positions.
