### ISSUE TITLE
Add Structure and Account Domain Objects under the Brokerage Account Parent Class

### ISSUE THREAD

**Issue by GalaJoe** [galatea-associates/fuse-test-data-gen#50]
Issue Description
---
Add Account Directory and Factory class structure.

Design
---

Add domain factory directories and classes to support the following Account structure:
Account [dir]
->Brokerage Account [abstract]
-> -> InternalCounterparty [impl]
-> -> ExternalCounterparty [abstract]
-> -> -> Contra (ECP) [impl]
-> -> -> ICP Holding [impl]
-> -> ->Depot Claim [impl]
-> -> Depot [impl]

Documentation Changes
---
1. Documentation of the module and new classes must follow the Numpy format as used throughout the rest of the project.

2. The Data Generator Attributes document must be updated to reflect the addition of an object, as well as the alteration of Account attributes of objects referencing an account: https://docs.google.com/document/d/1IB_-k16uhSBJWg2_s0pD2Vh3WZjTFALFYV6Ip9jM_4Q/edit

Documentation updated with new account objects. No attributes populated as of yet

Test Evidence
---
No tests as the parent can not be instantiated or written to the database. The tests will need to be implement with each implemnted class.

Validation in Develop
---

**Comment by GalateaTom** [comment]
I know what the Description is getting at, but I don't understand what "This should instead be a relation from an Account object, to dependent ones" means
