### ISSUE TITLE
Make the upload to Google drive optional: Implement any required fixes to get the GDrive upload working with the current implementation of the data generator

### ISSUE THREAD

**Issue by GalaJames** [galatea-associates/fuse-test-data-gen#6]
Issue Description
---
The data generator needs to be able to write the files it generates to a Google Drive location as an option. The location, directory and boolean option should all be configurable by the user.

Design
---
- Add 'upload_to_google_drive' option to the user facing config for each domain object. 
- When the flag is set to TRUE, the output_directory option should point to a G Drive directory.
- Ensure that when the flag is set to TRUE, the google drive connector pushes generated files to the desired G Drive location

Documentation Changes
---
- Update the README and the runbook with the new upload_to_google_drive flag
- Modify the numpy docs for the google_drive_connector

Test Evidence
---
- Ensure all existing tests in the suite still pass
- [Is it worth mocking out the connector to ensure test spass with upload = TRUE?]

Validation in Develop
---
-Verify that when running with uploda_to_google_drive= TRUE, the written files can be found on GDrive in the desired location

**Comment by GalaJames** [comment]
Using the new config.json file, added a key "upload_to_google_drive", which has a true/false value, this is passed to the "Generatable" class and used to determine whether to push the output to Google drive.

**Comment by j-barber** [comment]
Can you document this in the readme?

**Comment by GalaJames** [comment]
Added a section in the readme to cover Google drive uploading.  It talks about how to enable/disable the upload, but could do with some fleshing out about how the upload actually works, maybe track this in a separate issue.

**Comment by j-barber** [comment]
Is it worth including where in gDrive the files end up in the readme?

**Comment by GalaJames** [comment]
I've now refactored and tidied up the Google Drive logic and added the following to the readme:

### Uploading to Google Drive
The uploading of files to Google is optional and controlled at the domain object level.  This is configured by the "upload_to_google_drive" value (true or false), shown in the domain object configuration JSON above.

An optional command line parameter --g-drive-root can be supplied, which represents the Google Drive ID of a folder where you would like the files uploaded to.  If this parameter isn't supplied, the files will be uploaded to the root of your own Google drive.

When files are uploaded to Google drive, they will be uploaded into a folder with today's date (YYYY-MM-DD) as the name.  If the folder doesn't exist for today, it will be created.  If you are re-uploading the same files on a date where they have already been uploaded, the existing version(s) will be kept using the Google Drive versioning functionality.  To see the version history of a given file, you can right-click on a file in Google Drive and select "Manage Versions".

When uploading to Google Drive for the first time, you will be required to login using your Galatea Google account, a browser window should automatically load to allow you do this.  Once you have done this, an authentication token file "token.pickle" will be downloaded onto your machine.  When running the service remotely, it is important to ensure that a valid token.pickle file exists in the same directory as the application.

TODO: Investigate the use of the Google service accounts for Google Drive connectivity
