### ISSUE TITLE
Refactor the domain objects to be true factories / generators

### ISSUE THREAD

**Issue by tonasanya** [galatea-associates/fuse-test-data-gen#61]
Issue Description
---
The domain objects are not true domain objects but are domain object factories (or generators) that create dictionaries containing the domain object fields. 

Decide on behaviour and naming convention: Are these factories or generators? 
Rename the domain objects appropriately to show that they are factories/ generators.
Add domain object specific config (normal and custom) to the factory/generator so that these can be passed around instead of the config itself. 

Design
---
Refactor to include the custom and normal config in the class as a dictionary. 

Refactor parts of the code that use the domain objects and the config to use just the factory/generator

Documentation Changes
---
Update class documentation

Test Evidence
---
No new tests required but make sure existing tests are refactored to work

Validation in Develop
---

**Comment by GalaJoe** [comment]
Issue edited to be refactoring of current methods, arguments, variables etc. to adhere to "factory" naming convention.

Storage of configuration within factories has been resolved by issue #146 

Pythons implementation of generators not part of the MVP. A new issue will be raised for this for Sprint 4.
