### ISSUE TITLE
Validate output of existing codebase

### ISSUE THREAD

**Issue by GalaJames** [galatea-associates/fuse-test-data-gen#8]

**Comment by j-barber** [comment]
Specifically, we want to validate that references between datasets make sense. E.g. Accounts and Instruments from the Positions and Trades files are represented in the Accounts file and Instruments file.

**Comment by GalaJames** [comment]
Ran the original data generator with all domain objects enabled and confirmed that instances whereby domain objects were referenced by other domain objects correctly used the identifiers generated to ensure a valid relationship.

**Comment by j-barber** [comment]
Some examples from the run (https://drive.google.com/drive/folders/1IcuDZAx58zzp5Q4BI6G7Xxd01NTmTfjk)

Instruments on Swap Positions, Stock Loan Positions data sets are selected from the Instruments list:
![image](https://user-images.githubusercontent.com/23705265/59698191-28bf8f80-91bd-11e9-876d-e29265e69b2b.png)
![image](https://user-images.githubusercontent.com/23705265/59698254-4db40280-91bd-11e9-903a-933551867034.png)
![image](https://user-images.githubusercontent.com/23705265/59698152-180f1980-91bd-11e9-8f82-e67915d262bd.png)
